endpoints:
  shutdown:
    enabled: true
    
server:
  port: 8888
 
spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/rgalango/microservice-poc-config/
          uri: https://github.com/rgalango/archaius-config